Many upgrades to newer version of libraries. Switched to ant 1.8.2 which is the version embedded by maven-antrun-plugin v1.7. Otherwise we may encounter conflicts (java.lang.NoSuchMethodError: org.apache.tools.ant.util.FileUtils.getFileUtils) etc...
Ant version is now handled by a single property ${ant.version}